site_name: Map Action Model
nav:
  - Welcom: index.md
  - System Arch : systemArch.md
  - Data pre-processing: dataPreprocessing.md
  - Model fine tuning : modelFinetuning.md
  - Data fetching: dataFetching.md
  - Model inference: modelEvaluation.md
  - Model training: modelTraining.md

theme: 
  name: 'material'

plugins:
  - search
  - mkdocstrings:
      handlers:
          python:
            paths: [code]