site_name: Map Action Model
nav:
  - Welcom: index.md
  - System Arch : systemArch.md
  - Image annotation process : imageAnnotation.md
  - Data pre-processing: dataPreprocessing.md
  - Model fine tuning : modelFinetuning.md
  - Data fetching: dataFetching.md
  - Model inference: modelEvaluation.md
  - Model training: modelTraining.md
  - Setup and Run: install.md
  - Contrubition-guideline: contrubition-guideline.md
  
theme: 
  name: 'mkdocs'

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
          python:
            paths: [code]