artifact_location: /home/yugo19/map-action/Map-Action-Model/code/map_action_yolo_detection/runs/mlflow/0
creation_time: 1701259596097
experiment_id: '0'
last_update_time: 1701259596097
lifecycle_stage: active
name: Default
