artifact_location: /home/yugo19/map-action/Map-Action-Model/code/map_action_yolo_detection/runs/mlflow/452260836794962566
creation_time: 1701259596109
experiment_id: '452260836794962566'
last_update_time: 1701259596109
lifecycle_stage: active
name: /Shared/YOLOv8
