version: "3.9"

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  zenml:
    image: zenmldocker/zenml-server
    ports:
      - "8080:8080"
    environment:
      - ZENML_STORE_URL=${ZENML_STORE_URL}
      - ZENML_DEFAULT_USER_NAME=${ZENML_DEFAULT_USER_NAME}
      - ZENML_DEFAULT_USER_PASSWORD=${ZENML_DEFAULT_USER_PASSWORD}
    links:
      - postgres
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
