name: zenml server config

on:
  push:
    branches:
      - main

jobs:
  zenml-build-and-run:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Run Docker Compose
      env: 
        MYSQL_ROOT_PASSORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
        ZENML_DEFAULT_USER_NAME: ${{secrets.ZENML_DEFAULT_USER_NAME}}
        ZENML_DEFAULT_USER_PASSWORD: ${{secrets.ZENML_DEFAULT_USER_PASSWORD}}
        ZENML_STORE_URL: ${{secrets.ZENML_STORE_URL}}
      working-directory: zenml_config
      run: docker-compose -f zenml_conf.yml up --build 
